language: node_js
node_js:
- 12
cache:
  directories:
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: yannick-mayeur
jobs:
  include:
  - stage: test
    name: lint
    script:
    - npm run lint
  - stage: deploy-prod
    script: skip
    deploy:
      - skip_cleanup: true
        provider: script
        script: bash .travis/deploy.sh production
        on:
          branch: master
      - skip_cleanup: true
        provider: script
        script: bash .travis/deploy.sh staging
        on:
          branch: dev

before_deploy:
- openssl aes-256-cbc -K $encrypted_527885dea4dd_key -iv $encrypted_527885dea4dd_iv
  -in travis.enc -out .travis/travis -d
