version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: polyteach-db
      POSTGRES_PASSWORD: foobar
    ports:
      - 5432:5432
  polyteach-back:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
